version: "3.9"

services:
    postgres-orders:
        image: postgres
        ports:
          -  "5434:5432"
        env_file:
          -  database.env
        volumes:
          -  ${HOME}/postgres-data-product/:/var/lib/postgresql/data:Z
    
      